get:
  tags:
    - Repo
  summary: Get the config file
  parameters:
    - in: path
      name: namespace
      required: true
      schema:
        type: string
    - in: path
      name: name
      required: true
      schema:
        type: string
  responses:
    '200':
      description: Config 
      content:
        application/json:
          schema:
            $ref: '../../schemas/Config.yaml'
    '401': 
      $ref: '../../responses.yaml#/401Unauthorized'
    '402':
      $ref: '../../responses.yaml#/402PaymentRequired'
    '403': 
      $ref: '../../responses.yaml#/403Forbidden'
    '404': 
      $ref: '../../responses.yaml#/404NotFound'
    '422': 
      $ref: '../../responses.yaml#/422UnprocessableEntity'
    '500':
      $ref: '../../responses.yaml#/500InternalError'