get:
  tags:
    - Repo
  summary: Get the review of the user.
  parameters:
    - in: path
      name: namespace
      required: true
      schema:
        type: string
    - in: path
      name: name
      required: true
      schema:
        type: string
    - in: path
      name: number
      required: true
      schema:
        type: integer
        description: The deployment number.
  responses:
    '200':
      description: Return the review.
      content:
        application/json:
          schema:
            $ref: '../../schemas/Review.yaml'
    '401': 
      $ref: '../../responses.yaml#/401Unauthorized'
    '402':
      $ref: '../../responses.yaml#/402PaymentRequired'
    '403': 
      $ref: '../../responses.yaml#/403Forbidden'
    '404':
      $ref: '../../responses.yaml#/404NotFound'
    '500':
      $ref: '../../responses.yaml#/500InternalError'
patch:
  tags:
    - Repo
  summary: Update the review of the user if it exist.
  parameters:
    - in: path
      name: namespace
      required: true
      schema:
        type: string
    - in: path
      name: name
      required: true
      schema:
        type: string
    - in: path
      name: number
      required: true
      schema:
        type: integer
        description: The deployment number.
  requestBody:
    content:
      application/json:
        schema:
          type: object
          properties:
            status:
              type: string
              enum:
                - approved
                - rejected
            comment:
              type: string
              description: Leave the comment with the review.
          required:
            - status
  responses:
    '200':
      description: Return the review.
      content:
        application/json:
          schema:
            $ref: '../../schemas/Review.yaml'
    '401': 
      $ref: '../../responses.yaml#/401Unauthorized'
    '402':
      $ref: '../../responses.yaml#/402PaymentRequired'
    '403': 
      $ref: '../../responses.yaml#/403Forbidden'
    '404':
      $ref: '../../responses.yaml#/404NotFound'
    '422':
      $ref: '../../responses.yaml#/422UnprocessableEntity'
    '500':
      $ref: '../../responses.yaml#/500InternalError'