get:
  tags:
    - Repo
  summary: Get the deployments by the number.
  parameters:
    - in: path
      name: namespace
      required: true
      schema:
        type: string
    - in: path
      name: name
      required: true
      schema:
        type: string
    - in: path
      name: number
      required: true
      schema:
        type: integer
        description: The deployment number.
  responses:
    '200':
      description: Deployment 
      content:
        application/json:
          schema:
            $ref: '../../schemas/Deployment.yaml'
    '401': 
      $ref: '../../responses.yaml#/401Unauthorized'
    '402':
      $ref: '../../responses.yaml#/402PaymentRequired'
    '403': 
      $ref: '../../responses.yaml#/403Forbidden'
    '404': 
      $ref: '../../responses.yaml#/404NotFound'
    '422':
      $ref: '../../responses.yaml#/422UnprocessableEntity'
      description: The deployment payload or the configuration is invalid.
    '500':
      $ref: '../../responses.yaml#/500InternalError'
put: 
  tags:
    - Repo
  summary: Create a remote deployment when the status of the deployment is 'waiting'.
  parameters:
    - in: path
      name: namespace
      required: true
      schema:
        type: string
    - in: path
      name: name
      required: true
      schema:
        type: string
    - in: path
      name: number
      required: true
      schema:
        type: integer
        description: The deployment number.
  responses:
    '200':
      description: Deployment 
      content:
        application/json:
          schema:
            $ref: '../../schemas/Deployment.yaml'
    '401': 
      $ref: '../../responses.yaml#/401Unauthorized'
    '402':
      $ref: '../../responses.yaml#/402PaymentRequired'
    '403': 
      $ref: '../../responses.yaml#/403Forbidden'
    '404': 
      $ref: '../../responses.yaml#/404NotFound'
    '422':
      $ref: '../../responses.yaml#/422UnprocessableEntity'
      description: The configuration is invalid or it is not approved.
    '500':
      $ref: '../../responses.yaml#/500InternalError'