post:
  tags:
    - Repo
  summary: Create a new remote deployment status.
  parameters:
    - in: path
      name: namespace
      required: true
      schema:
        type: string
    - in: path
      name: name
      required: true
      schema:
        type: string
    - in: path
      name: number
      required: true
      schema:
        type: integer
        description: The deployment number.
  requestBody:
    content:
      application/json:
        schema:
          type: object
          properties:
            status:
              type: string
            description:
              type: string
            log_url:
              type: string
          required:
            - status
  responses:
    '200':
      description: Return the deployment status.
      content:
        application/json:
          schema:
            $ref: '../../schemas/RemoteDeploymentStatus.yaml'
    '401': 
      $ref: '../../responses.yaml#/401Unauthorized'
    '402':
      $ref: '../../responses.yaml#/402PaymentRequired'
    '403': 
      $ref: '../../responses.yaml#/403Forbidden'
    '422':
      $ref: '../../responses.yaml#/422UnprocessableEntity'
    '500':
      $ref: '../../responses.yaml#/500InternalError'