site_name: Gitploy
site_url: https://doc.gitploy.io
theme: 
  name: material
  palette:
    primary: deep purple
    accent: deep purple 
  logo: images/logo.svg
  favicon: images/favicon.ico
  icon:
    repo: fontawesome/brands/github
nav:
  - Home: index.md
  - Concepts: 
    - "How it works": concepts/how-it-work.md
    - "deploy.yml": concepts/deploy.yml.md
    - Deployment: concepts/deployment.md
    - Lock: concepts/lock.md
    - Permission: concepts/permission.md
    - "Self-hosted Server": concepts/self-hosted-server.md
    - Chatops: concepts/chatops.md
    - License: concepts/license.md
  - Tasks:
    - Installation: tasks/installation.md
    - Database: tasks/database.md
    - "First Deployment": tasks/first-deployment.md
    - Integration: tasks/integration.md
  - References: 
    - Configurations: references/configurations.md
    - "deploy.yml": references/deploy.yml.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gitploy-io
  version:
    provider: mike
copyright: Copyright &copy; 2021 Gitploy.IO
repo_name: gitploy-io/gitploy
repo_url: https://github.com/gitploy-io/gitploy
edit_uri: edit/main/docs/
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences