site_name: Gitploy
site_url: https://doc.gitploy.io
theme: 
  name: material
  palette:
    primary: deep purple
    accent: deep purple 
nav:
  - Home: index.md
  - Concepts: 
    - "How it works": concepts/how-it-work.md
    - "deploy.yaml": concepts/deploy.yml.md
    - Permission: concepts/permission.md
    - Chatops: concepts/chatops.md
    - License: concepts/license.md
  - Tasks:
    - Installation: tasks/installation.md
    - Integration: tasks/integration.md
  - References: 
    - Configurations: references/configurations.md