openapi: '3.0.2'
info:
  title: gitploy.
  version: '1.0'
servers:
  - url: https://gitploy.jp.ngrok.io/v1
  - url: https://cloud.gitploy.io/v1
paths:
  /sync:
    post:
      tags:
        - common
      summary: Synchronize with SCM
      responses:
        '200':
          description: OK
        '401': 
          $ref: '#/components/responses/401Unauthorized'
        '500':
          $ref: '#/components/responses/500InternalError'
  /repos:
    get:
      tags:
        - Repo
      summary: List repositories the user can access
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
            description: The page number
      responses:
        '200':
          description: Repositories
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Repositories'
        '401': 
          $ref: '#/components/responses/401Unauthorized'
        '500':
          $ref: '#/components/responses/500InternalError'
  /repos/{repoId}:
    get:
      tags:
        - Repo
      summary: Get repository
      parameters:
        - in: path
          name: repoId
          required: true
          schema:
            type: integer
            description: The repository id
      responses:
        '200':
          description: Repository
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Repository'
        '401': 
          $ref: '#/components/responses/401Unauthorized'
        '403': 
          $ref: '#/components/responses/403Forbidden'
        '500':
          $ref: '#/components/responses/500InternalError'
  /repos/{repoId}/commits:
    get:
      tags:
        - Repo
      summary: List commits
      parameters:
        - in: path
          name: repoId
          required: true
          schema:
            type: integer
            description: The repository id
        - in: query
          name: branch
          schema:
            type: string
            default: 
            description: > 
              The branch to start listing commits from. 
              Default - the repository’s default branch.
        - in: query
          name: page
          schema:
            type: integer
            default: 1
            description: The page number
        - in: query
          name: per_page
          schema:
            type: integer
            default: 30
            description: The page number
      responses:
        '200':
          description: Commits
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Commits'
        '401': 
          $ref: '#/components/responses/401Unauthorized'
        '403': 
          $ref: '#/components/responses/403Forbidden'
        '500':
          $ref: '#/components/responses/500InternalError'
  /repos/{repoId}/commits/{sha}:
    get:
      tags:
        - Repo
      summary: List commits
      parameters:
        - in: path
          name: repoId
          required: true
          schema:
            type: integer
            description: The repository id
        - in: path
          name: sha
          required: true
          schema:
            type: string
            description: The commit sha
      responses:
        '200':
          description: Commit
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Commit'
        '401': 
          $ref: '#/components/responses/401Unauthorized'
        '403': 
          $ref: '#/components/responses/403Forbidden'
        '500':
          $ref: '#/components/responses/500InternalError'

security:
  - BearerAuth: []
  - OAuth2:
    - read

components:
  schemas:
    Repositories:
      type: array
      items:
        $ref: '#/components/schemas/Repository'
    Repository:
      type: object
      properties:
        id:
          type: integer
        namespace:
          type: string
          description: Repository owner
        name:
          type: string
        full_name:
          type: string
          description: Full name of repository
        description:
          type: string
        synched_at:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
    Commits:
      type: array
      items:
        $ref: '#/components/schemas/Commit'
    Commit:
      type: object
      properties:
        sha:
          type: string
        message:
          type: string
        is_pull_request:
          type: boolean
    Error:
      type: object
      properties:
        message: 
          type: string

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      description: Hash key of user
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://github.com/oauth/authorize
          tokenUrl: https://github.com/oauth/token
          scopes:
            read: Grants read access
            write: Grants write access
            admin: Grants access to admin operations
    
  responses:
    401Unauthorized:
      description: Unauthorized access
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    403Forbidden:
      description: Permisson denied
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
        
    500InternalError:
      description: Server internal error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
