// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/gitploy-io/gitploy/ent/perm"
	"github.com/gitploy-io/gitploy/ent/repo"
	"github.com/gitploy-io/gitploy/ent/user"
)

// Perm is the model entity for the Perm schema.
type Perm struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// RepoPerm holds the value of the "repo_perm" field.
	RepoPerm perm.RepoPerm `json:"repo_perm"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id"`
	// RepoID holds the value of the "repo_id" field.
	RepoID int64 `json:"repo_id"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PermQuery when eager-loading is set.
	Edges PermEdges `json:"edges"`
}

// PermEdges holds the relations/edges for other nodes in the graph.
type PermEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Repo holds the value of the repo edge.
	Repo *Repo `json:"repo,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PermEdges) UserOrErr() (*User, error) {
	if e.loadedTypes[0] {
		if e.User == nil {
			// The edge user was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.User, nil
	}
	return nil, &NotLoadedError{edge: "user"}
}

// RepoOrErr returns the Repo value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PermEdges) RepoOrErr() (*Repo, error) {
	if e.loadedTypes[1] {
		if e.Repo == nil {
			// The edge repo was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: repo.Label}
		}
		return e.Repo, nil
	}
	return nil, &NotLoadedError{edge: "repo"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Perm) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case perm.FieldID, perm.FieldUserID, perm.FieldRepoID:
			values[i] = new(sql.NullInt64)
		case perm.FieldRepoPerm:
			values[i] = new(sql.NullString)
		case perm.FieldCreatedAt, perm.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Perm", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Perm fields.
func (pe *Perm) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case perm.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			pe.ID = int(value.Int64)
		case perm.FieldRepoPerm:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field repo_perm", values[i])
			} else if value.Valid {
				pe.RepoPerm = perm.RepoPerm(value.String)
			}
		case perm.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				pe.CreatedAt = value.Time
			}
		case perm.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				pe.UpdatedAt = value.Time
			}
		case perm.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				pe.UserID = value.Int64
			}
		case perm.FieldRepoID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field repo_id", values[i])
			} else if value.Valid {
				pe.RepoID = value.Int64
			}
		}
	}
	return nil
}

// QueryUser queries the "user" edge of the Perm entity.
func (pe *Perm) QueryUser() *UserQuery {
	return (&PermClient{config: pe.config}).QueryUser(pe)
}

// QueryRepo queries the "repo" edge of the Perm entity.
func (pe *Perm) QueryRepo() *RepoQuery {
	return (&PermClient{config: pe.config}).QueryRepo(pe)
}

// Update returns a builder for updating this Perm.
// Note that you need to call Perm.Unwrap() before calling this method if this Perm
// was returned from a transaction, and the transaction was committed or rolled back.
func (pe *Perm) Update() *PermUpdateOne {
	return (&PermClient{config: pe.config}).UpdateOne(pe)
}

// Unwrap unwraps the Perm entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pe *Perm) Unwrap() *Perm {
	tx, ok := pe.config.driver.(*txDriver)
	if !ok {
		panic("ent: Perm is not a transactional entity")
	}
	pe.config.driver = tx.drv
	return pe
}

// String implements the fmt.Stringer.
func (pe *Perm) String() string {
	var builder strings.Builder
	builder.WriteString("Perm(")
	builder.WriteString(fmt.Sprintf("id=%v", pe.ID))
	builder.WriteString(", repo_perm=")
	builder.WriteString(fmt.Sprintf("%v", pe.RepoPerm))
	builder.WriteString(", created_at=")
	builder.WriteString(pe.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", updated_at=")
	builder.WriteString(pe.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", user_id=")
	builder.WriteString(fmt.Sprintf("%v", pe.UserID))
	builder.WriteString(", repo_id=")
	builder.WriteString(fmt.Sprintf("%v", pe.RepoID))
	builder.WriteByte(')')
	return builder.String()
}

// Perms is a parsable slice of Perm.
type Perms []*Perm

func (pe Perms) config(cfg config) {
	for _i := range pe {
		pe[_i].config = cfg
	}
}
