ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: dev.gitploy.io
      paths:
        - path: /
          pathType: Prefix
  tls:
   - secretName: gitploy-dev-tls
     hosts:
       - dev.gitploy.io

resources:
  requests:
    cpu: 50m
    memory: 128Mi

env:
  GITPLOY_DEBUG_MODE: "true"
  GITPLOY_SERVER_HOST: "dev.gitploy.io"
  GITPLOY_SERVER_PROTO: https
  GITPLOY_ADMIN_USERS: "hanjunlee"
  GITPLOY_MEMBER_ENTRIES: "gitploy-io"
  GITPLOY_PROMETHEUS_ENABLED: "true"

extraSecretNamesForEnvFrom:
  - gitploy-dev-secret

persistentVolume:
  enabled: true