replicaCount: 2

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: cloud.gitploy.io
      paths:
        - path: /
          pathType: Prefix
  tls:
   - secretName: gitploy-prod-tls
     hosts:
       - cloud.gitploy.io

resources:
  requests:
    cpu: 100m
    memory: 256Mi

env:
  GITPLOY_DEBUG_MODE: "true"
  GITPLOY_SERVER_HOST: "cloud.gitploy.io"
  GITPLOY_SERVER_PROTO: https
  GITPLOY_ADMIN_USERS: "hanjunlee"
  GITPLOY_GITHUB_SCOPES: "public_repo,read:user,read:org"
  GITPLOY_STORE_DRIVER: "mysql"

extraSecretNamesForEnvFrom:
  - gitploy-prod-secret