name: deploy-to-cloud

on:
  deployment

jobs:
  deploy-local:
    runs-on: ubuntu-latest
    if: ${{ github.event.deployment.environment == 'local' }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      - 
        name: Deploy successfully
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          deployment_id: ${{ github.event.deployment.id }}
          state: "success"
          token: "${{ github.token }}"
          description: Finish to deploy successfully.
    
  deploy-dev:
    runs-on: ubuntu-latest
    # https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#deployment
    if: ${{ github.event.deployment.environment == 'dev' }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Create values.yaml
        uses: finnp/create-file-action@master
        env:
          FILE_NAME: "./.github/values.yaml"
          FILE_BASE64: "aW5ncmVzczoKICBlbmFibGVkOiB0cnVlCiAgYW5ub3RhdGlvbnM6CiAgICBrdWJlcm5ldGVzLmlvL2luZ3Jlc3MuY2xhc3M6IG5naW54CiAgICBjZXJ0LW1hbmFnZXIuaW8vY2x1c3Rlci1pc3N1ZXI6ICJsZXRzZW5jcnlwdC1wcm9kIgogIGhvc3RzOgogICAgLSBob3N0OiBkZXYuZ2l0cGxveS5pbwogICAgICBwYXRoczoKICAgICAgICAtIHBhdGg6IC8KICAgICAgICAgIHBhdGhUeXBlOiBQcmVmaXgKICB0bHM6CiAgIC0gc2VjcmV0TmFtZTogZ2l0cGxveS1kZXYtdGxzCiAgICAgaG9zdHM6CiAgICAgICAtIGRldi5naXRwbG95LmlvCgpyZXNvdXJjZXM6CiAgcmVxdWVzdHM6CiAgICBjcHU6IDUwbQogICAgbWVtb3J5OiAxMjhNaQoKZW52OgogIEdJVFBMT1lfREVCVUdfTU9ERTogInRydWUiCiAgR0lUUExPWV9TRVJWRVJfSE9TVDogImRldi5naXRwbG95LmlvIgogIEdJVFBMT1lfU0VSVkVSX1BST1RPOiBodHRwcwogIEdJVFBMT1lfQURNSU5fVVNFUlM6ICJoYW5qdW5sZWUiCiAgR0lUUExPWV9NRU1CRVJfRU5UUklFUzogImdpdHBsb3ktaW8iCiAgR0lUUExPWV9QUk9NRVRIRVVTX0VOQUJMRUQ6ICJ0cnVlIgoKZXh0cmFTZWNyZXROYW1lc0ZvckVudkZyb206CiAgLSBnaXRwbG95LWRldi1zZWNyZXQKCnBlcnNpc3RlbnRWb2x1bWU6CiAgZW5hYmxlZDogdHJ1ZQo="
      - 
        name: Start to deploy
        uses: chrnorm/deployment-status@releases/v1
        with:
          deployment_id: ${{ github.event.deployment.id }}
          description: Start to deploy to the Kubernetes
          state: "in_progress"
          token: "${{ github.token }}"
      - 
        name: Deploy 
        uses: WyriHaximus/github-action-helm3@v2
        with:
          # Upgrade to the version.
          exec: >
            helm repo add gitployio https://gitploy-io.github.io/helm-chart/;
            helm upgrade gitploy-dev gitployio/gitploy 
            --install
            --atomic 
            --namespace=gitploy
            -f .github/values.yaml
            --set=image.tag=${GITHUB_REF#refs/tags/v}
            --set=image.pullPolicy=Always
            --description="Upgrade to ${GITHUB_REF#refs/tags/}"
          kubeconfig: '${{ secrets.KUBECONFIG }}'
      - 
        name: Deploy successfully
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          deployment_id: ${{ github.event.deployment.id }}
          description: Finish to deploy successfully.
          state: "success"
          token: "${{ github.token }}"
      - 
        name: Deploy failed
        if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          deployment_id: ${{ github.event.deployment.id }}
          description: Failed to deploy.
          state: "failure"
          token: "${{ github.token }}"
    
  deploy-production:
    runs-on: ubuntu-latest
    # https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#deployment
    if: ${{ github.event.deployment.environment == 'production' }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Create values.yaml
        uses: finnp/create-file-action@master
        env:
          FILE_NAME: "./.github/values.yaml"
          FILE_BASE64: "cmVwbGljYUNvdW50OiAyCgppbmdyZXNzOgogIGVuYWJsZWQ6IHRydWUKICBhbm5vdGF0aW9uczoKICAgIGt1YmVybmV0ZXMuaW8vaW5ncmVzcy5jbGFzczogbmdpbngKICAgIGNlcnQtbWFuYWdlci5pby9jbHVzdGVyLWlzc3VlcjogImxldHNlbmNyeXB0LXByb2QiCiAgaG9zdHM6CiAgICAtIGhvc3Q6IGNsb3VkLmdpdHBsb3kuaW8KICAgICAgcGF0aHM6CiAgICAgICAgLSBwYXRoOiAvCiAgICAgICAgICBwYXRoVHlwZTogUHJlZml4CiAgdGxzOgogICAtIHNlY3JldE5hbWU6IGdpdHBsb3ktcHJvZC10bHMKICAgICBob3N0czoKICAgICAgIC0gY2xvdWQuZ2l0cGxveS5pbwoKcmVzb3VyY2VzOgogIHJlcXVlc3RzOgogICAgY3B1OiAxMDBtCiAgICBtZW1vcnk6IDI1Nk1pCgplbnY6CiAgR0lUUExPWV9ERUJVR19NT0RFOiAidHJ1ZSIKICBHSVRQTE9ZX1NFUlZFUl9IT1NUOiAiY2xvdWQuZ2l0cGxveS5pbyIKICBHSVRQTE9ZX1NFUlZFUl9QUk9UTzogaHR0cHMKICBHSVRQTE9ZX0FETUlOX1VTRVJTOiAiaGFuanVubGVlIgogIEdJVFBMT1lfR0lUSFVCX1NDT1BFUzogInB1YmxpY19yZXBvLHJlYWQ6dXNlcixyZWFkOm9yZyIKICBHSVRQTE9ZX1NUT1JFX0RSSVZFUjogIm15c3FsIgoKZXh0cmFTZWNyZXROYW1lc0ZvckVudkZyb206CiAgLSBnaXRwbG95LXByb2Qtc2VjcmV0Cg=="
      - 
        name: Start to deploy
        uses: chrnorm/deployment-status@releases/v1
        with:
          deployment_id: ${{ github.event.deployment.id }}
          description: Start to deploy to the Kubernetes
          state: "in_progress"
          token: "${{ github.token }}"
      - 
        name: Deploy 
        uses: WyriHaximus/github-action-helm3@v2
        with:
          # Upgrade to the version.
          exec: >
            helm repo add gitployio https://gitploy-io.github.io/helm-chart/;
            helm upgrade gitploy-prod gitployio/gitploy 
            --install
            --atomic 
            --namespace=gitploy
            -f .github/values.yaml
            --set=image.tag=${GITHUB_REF#refs/tags/v}
            --set=image.pullPolicy=Always
            --description="Upgrade to ${GITHUB_REF#refs/tags/}"
          kubeconfig: '${{ secrets.KUBECONFIG }}'
      - 
        name: Deploy successfully
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          deployment_id: ${{ github.event.deployment.id }}
          description: Finish to deploy successfully.
          state: "success"
          token: "${{ github.token }}"
      - 
        name: Deploy failed
        if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          deployment_id: ${{ github.event.deployment.id }}
          description: Failed to deploy.
          state: "failure"
          token: "${{ github.token }}"
    