name: publish

on:
  # push:
  #   tags:
  #     - 'v*.*.*'
  pull_request:

jobs:
  # publish-image:
  #   runs-on: ubuntu-latest
  #   steps:
  #     -
  #       name: Checkout
  #       uses: actions/checkout@v2
  #     -
  #       name: Docker meta
  #       id: docker_meta
  #       uses: crazy-max/ghaction-docker-meta@v1
  #       with:
  #         images: gitployio/gitploy
  #         tag-semver: |
  #           {{version}}
  #           {{major}}.{{minor}}
  #     -
  #       name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1
  #     -
  #       name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1
  #     -
  #       name: Login to DockerHub
  #       uses: docker/login-action@v1 
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     -
  #       name: Build and push
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: .
  #         platforms: linux/amd64  # ,linux/arm64
  #         push: true
  #         tags: ${{ steps.docker_meta.outputs.tags }}

  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v2
      - 
        name: Create requirements.txt
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: requirements.txt
          FILE_DATA: |
            pymdown-extensions==8.2
      - 
        name: Publish docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          CUSTOM_DOMAIN: docs.gitploy.io
          REQUIREMENTS: requirements.txt
