name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v2
      - 
        name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.41
          args: -D errcheck --timeout 2m
      - 
        uses: actions/setup-go@v1
        with:
          go-version: '1.17'
      - 
        run: go test -cpu 4 -coverprofile .testCoverage.txt $(go list ./... | grep -v model/ent | grep -v mock)
        env:
          GIN_MODE: release

  react-test:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v2
      - 
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
          cache: 'npm'
          cache-dependency-path: ui/package-lock.json
      - 
        run: npm install
        working-directory: ui
      - 
        run: npm run lint
        working-directory: ui
