// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Approval is the predicate function for approval builders.
type Approval func(*sql.Selector)

// Callback is the predicate function for callback builders.
type Callback func(*sql.Selector)

// ChatUser is the predicate function for chatuser builders.
type ChatUser func(*sql.Selector)

// Comment is the predicate function for comment builders.
type Comment func(*sql.Selector)

// Deployment is the predicate function for deployment builders.
type Deployment func(*sql.Selector)

// DeploymentStatistics is the predicate function for deploymentstatistics builders.
type DeploymentStatistics func(*sql.Selector)

// DeploymentStatus is the predicate function for deploymentstatus builders.
type DeploymentStatus func(*sql.Selector)

// Event is the predicate function for event builders.
type Event func(*sql.Selector)

// Lock is the predicate function for lock builders.
type Lock func(*sql.Selector)

// NotificationRecord is the predicate function for notificationrecord builders.
type NotificationRecord func(*sql.Selector)

// Perm is the predicate function for perm builders.
type Perm func(*sql.Selector)

// Repo is the predicate function for repo builders.
type Repo func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
