// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Perm is the predicate function for perm builders.
type Perm func(*sql.Selector)

// Repo is the predicate function for repo builders.
type Repo func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
